import crypto from "crypto"

// AES-256-GCM Configuration
const ALGORITHM = "aes-256-gcm"
const IV_LENGTH = 16
const SALT_LENGTH = 64
const TAG_LENGTH = 16
const KEY_LENGTH = 32

function getMasterKey() {
  const secret = process.env.ENCRYPTION_SECRET || process.env.JWT_SECRET
  if (!secret) throw new Error("Missing ENCRYPTION_SECRET in environment variables.")
  // Hash the secret to ensure it's exactly 32 bytes for AES-256
  return crypto.createHash("sha256").update(String(secret)).digest()
}

/**
 * Encrypts a sensitive string using AES-256-GCM.
 * Returns a cipher string containing iv:salt:authTag:encryptedData
 */
export function encryptData(text: string): string {
  const iv = crypto.randomBytes(IV_LENGTH)
  const salt = crypto.randomBytes(SALT_LENGTH)
  const masterKey = getMasterKey()
  
  // Scrypt key derivation
  const key = crypto.scryptSync(masterKey, salt, KEY_LENGTH)

  const cipher = crypto.createCipheriv(ALGORITHM, key, iv)
  
  let encrypted = cipher.update(text, "utf8", "hex")
  encrypted += cipher.final("hex")
  
  const authTag = cipher.getAuthTag().toString("hex")

  return `${iv.toString("hex")}:${salt.toString("hex")}:${authTag}:${encrypted}`
}

/**
 * Decrypts a cipher string generated by encryptData().
 */
export function decryptData(cipherText: string): string {
  const [ivHex, saltHex, authTagHex, encryptedHex] = cipherText.split(":")
  
  if (!ivHex || !saltHex || !authTagHex || !encryptedHex) {
    throw new Error("Invalid cipher text format")
  }

  const iv = Buffer.from(ivHex, "hex")
  const salt = Buffer.from(saltHex, "hex")
  const authTag = Buffer.from(authTagHex, "hex")
  
  const masterKey = getMasterKey()
  const key = crypto.scryptSync(masterKey, salt, KEY_LENGTH)

  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv)
  decipher.setAuthTag(authTag)

  let decrypted = decipher.update(encryptedHex, "hex", "utf8")
  decrypted += decipher.final("utf8")

  return decrypted
}
