version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: music-coin-db
    environment:
      POSTGRES_USER: musiccoin
      POSTGRES_PASSWORD: musiccoin_pass
      POSTGRES_DB: music_coin_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
